#
# build and test ext-jsonreader on Travis CI - https://travis-ci.org/
#

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script:
  - phpize
  - ./configure --enable-shared
  - make
  - make test
