#
# build and test ext-jsonreader on Travis CI - https://travis-ci.org/
#

language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - NO_INTERACTION="1" REPORT_EXIT_STATUS="1"

script:
  - phpize
  - ./configure --enable-shared
  - make
  - make test
